[package]
name = "palform-analysis"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.83"

serde-wasm-bindgen = { version = "0.6.5" }
wasm-bindgen = { version = "0.2.92", features = ["serde"] }
getrandom = { version = "*", features = ["js"] }
linfa = "0.8.0"
linfa-linear = "0.8.0"
interp = "2.0"
# waiting to upgrade: https://github.com/rust-ml/linfa/issues/357
ndarray = "0.16.1"
ndarray-stats = "0.6"

palform-client-common = { path = "../client-common", default-features = false, features = [
    "frontend-js",
] }
