[workspace]
members = [
    "packages/backend",
    "packages/migration",
    "packages/entities",
    "packages/client-common",
    "packages/google-fonts-generator",
    "packages/analysis",
    "packages/tsid",
    "packages/bench",
]
resolver = "2"
