FROM docker.io/rust:1-slim-trixie AS builder

RUN apt-get update
RUN apt-get install -y libssl-dev pkg-config

WORKDIR /usr/src/palform
COPY packages/backend packages/backend
COPY packages/analysis packages/analysis
COPY packages/bench packages/bench
COPY packages/client-common packages/client-common
COPY packages/crypto packages/crypto
COPY packages/entities packages/entities
COPY packages/migration packages/migration
COPY packages/google-fonts-generator packages/google-fonts-generator
COPY packages/tsid packages/tsid
COPY Cargo.toml Cargo.lock ./

RUN cargo install --path packages/backend --profile release

FROM docker.io/debian:trixie-slim
RUN apt-get update
RUN apt-get install -y libssl-dev pkg-config ca-certificates
RUN update-ca-certificates

COPY --from=builder /usr/local/cargo/bin/palform-backend /opt/palform-backend

CMD ["/opt/palform-backend", "server"]
