FROM docker.io/oven/bun:slim AS builder

ARG BACKEND_URL
ARG FRONTEND_URL

WORKDIR /app
COPY --parents packages/*/package.json .
COPY package.json bun.lock .

RUN mkdir packages/analysis-js && echo "{ \"name\": \"@palform/palform-analysis\" }" > packages/analysis-js/package.json
RUN mkdir packages/client-js && echo "{ \"name\": \"@palform/palform-client-common\" }" > packages/client-js/package.json
RUN mkdir packages/crypto-js && echo "{ \"name\": \"@palform/palform-crypto\" }" > packages/crypto-js/package.json

RUN bun install --frozen-lockfile

COPY packages packages

ENV PUBLIC_BACKEND_URL=$BACKEND_URL
ENV PUBLIC_APP_URL=$FRONTEND_URL
RUN bun run --cwd packages/landing build

ENV HOST=0.0.0.0
ENV PORT=4321
CMD ["bun", "run", "packages/landing/dist/server/entry.mjs"]
