// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type APIGenericAddress = { line1: string | null, line2: string | null, postal_code: string | null, locality: string | null, iso_3166_alpha_1_code: string | null, };
