// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionSubmission } from "./QuestionSubmission";
import type { TSIDDatabaseID } from "./TSIDDatabaseID";

export type InProgressSubmission = { form_id: TSIDDatabaseID, groups_completed: Array<TSIDDatabaseID>, questions: Array<QuestionSubmission>, };
