// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PalformDatabaseID } from "./PalformDatabaseID";
import type { QuestionSubmission } from "./QuestionSubmission";

export type InProgressSubmission = { form_id: PalformDatabaseID, groups_completed: Array<PalformDatabaseID>, questions: Array<QuestionSubmission>, };
