// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionSubmissionData } from "./QuestionSubmissionData";
import type { TSIDDatabaseID } from "./TSIDDatabaseID";

export type QuestionSubmission = { question_id: TSIDDatabaseID, data: QuestionSubmissionData, };
