// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { APIGenericAddress } from "./APIGenericAddress";
import type { APIGenericLocation } from "./APIGenericLocation";

export type QuestionSubmissionData = { "Text": { value: string, } } | { "Choice": { option: Array<string>, } } | { "Scale": { value: number | null, } } | { "Address": { address: APIGenericAddress, point: APIGenericLocation, } } | { "PhoneNumber": { calling_code: string, number: string, } } | { "FileUpload": { file_id: string, content_type: string, } } | { "Signature": { freeform: Array<Array<Array<number>>>, initial: string, full_name: string, } } | { "ChoiceMatrix": { options: Map<string, string[]>, } } | { "DateTime": { value: string, } } | { "Hidden": { value: string, } };
