// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PalformDatabaseID } from "./PalformDatabaseID";
import type { QuestionSubmissionData } from "./QuestionSubmissionData";

export type QuestionSubmission = { question_id: PalformDatabaseID, data: QuestionSubmissionData, };
