// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a prefixed, type-safe, resource-specific ID in your database.
 * The resource is defined by `Resource`: when deserializing, that resource must be matched when
 * reading the prefix. When serializing, that resource will be used to create the prefix.
 *
 * Internally, this stores a `TSID`, which is actually a `u64`. In your database, you should
 * probably store this `u64` instead of the base32-encoded prefixed string. The numbers are
 * time-ordered so you can sort your database with great performance.
 */
export type TSIDDatabaseID = string;
