//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use palform_tsid::{resources::{IDAdminPublicKey, IDAdminUser, IDOrganisation}, tsid::PalformDatabaseID};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "admin_public_key")]
pub struct Model {
    pub public_key: Vec<u8>,
    pub created_at: DateTime,
    pub expires_at: DateTime,
    #[sea_orm(unique)]
    pub cert_fingerprint: String,
    pub private_key_backup: Option<Vec<u8>>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: PalformDatabaseID<IDAdminPublicKey>,
    pub organisation_id: PalformDatabaseID<IDOrganisation>,
    pub user_id: PalformDatabaseID<IDAdminUser>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::admin_user::Entity",
        from = "Column::UserId",
        to = "super::admin_user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AdminUser,
    #[sea_orm(
        belongs_to = "super::organisation::Entity",
        from = "Column::OrganisationId",
        to = "super::organisation::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organisation,
}

impl Related<super::admin_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdminUser.def()
    }
}

impl Related<super::organisation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organisation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
