//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use super::sea_orm_active_enums::AdminUserEmailVerificationPurposeEnum;
use palform_tsid::{
    resources::{IDAdminUser, IDAdminUserEmailVerification},
    tsid::PalformDatabaseID,
};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "admin_user_email_verification")]
pub struct Model {
    pub user_id: PalformDatabaseID<IDAdminUser>,
    pub purpose: AdminUserEmailVerificationPurposeEnum,
    pub created_at: DateTime,
    pub expires_at: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: PalformDatabaseID<IDAdminUserEmailVerification>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
