//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use super::sea_orm_active_enums::AuditLogTargetResourceEnum;
use super::sea_orm_active_enums::AuditLogVerbEnum;
use palform_tsid::resources::{IDAdminUser, IDAuditLogEntry, IDOrganisation, IDUnknown};
use palform_tsid::tsid::PalformDatabaseID;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "audit_log_entry")]
pub struct Model {
    pub target_resource_type: AuditLogTargetResourceEnum,
    pub target_resource_id: Option<PalformDatabaseID<IDUnknown>>,
    pub verb: AuditLogVerbEnum,
    pub note: Option<String>,
    pub created_at: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: PalformDatabaseID<IDAuditLogEntry>,
    pub organisation_id: PalformDatabaseID<IDOrganisation>,
    pub user_id: PalformDatabaseID<IDAdminUser>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::admin_user::Entity",
        from = "Column::UserId",
        to = "super::admin_user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AdminUser,
    #[sea_orm(
        belongs_to = "super::organisation::Entity",
        from = "Column::OrganisationId",
        to = "super::organisation::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organisation,
}

impl Related<super::admin_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdminUser.def()
    }
}

impl Related<super::organisation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organisation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
