//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use palform_tsid::{
    resources::{IDFormBranding, IDTeam},
    tsid::PalformDatabaseID,
};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "form_branding_team_access")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub form_branding_id: PalformDatabaseID<IDFormBranding>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub team_id: PalformDatabaseID<IDTeam>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::form_branding::Entity",
        from = "Column::FormBrandingId",
        to = "super::form_branding::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    FormBranding,
    #[sea_orm(
        belongs_to = "super::team::Entity",
        from = "Column::TeamId",
        to = "super::team::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Team,
}

impl Related<super::form_branding::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FormBranding.def()
    }
}

impl Related<super::team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Team.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
