//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use palform_tsid::{
    resources::{IDOrganisation, IDOrganisationInvite},
    tsid::PalformDatabaseID,
};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "organisation_invite")]
pub struct Model {
    pub single_use: bool,
    pub created_at: DateTimeWithTimeZone,
    pub expires_at: DateTimeWithTimeZone,
    pub organisation_id: PalformDatabaseID<IDOrganisation>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: PalformDatabaseID<IDOrganisationInvite>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organisation::Entity",
        from = "Column::OrganisationId",
        to = "super::organisation::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organisation,
}

impl Related<super::organisation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organisation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
