//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use super::sea_orm_active_enums::OrganisationDeletionRequestStatusEnum;
use palform_tsid::{
    resources::{IDAdminUser, IDOrganisation, IDOrganisationDeletionRequest},
    tsid::PalformDatabaseID,
};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "organisation_deletion_request")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: PalformDatabaseID<IDOrganisationDeletionRequest>,
    pub organisation_id: PalformDatabaseID<IDOrganisation>,
    pub user_id: PalformDatabaseID<IDAdminUser>,
    pub include_user: bool,
    pub reason: String,
    pub status: OrganisationDeletionRequestStatusEnum,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
