//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use palform_tsid::{resources::IDOrganisationAuthConfig, tsid::PalformDatabaseID};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "organisation_auth_config")]
pub struct Model {
    pub oidc_discovery_url: String,
    pub client_id: String,
    pub client_secret: String,
    pub team_mapping_field_name: Option<String>,
    pub revoke_team_mappings: Option<bool>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: PalformDatabaseID<IDOrganisationAuthConfig>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::organisation::Entity")]
    Organisation,
}

impl Related<super::organisation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organisation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
