//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use palform_tsid::{
    resources::{IDFillAccessToken, IDForm, IDSubmission},
    tsid::PalformDatabaseID,
};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "submission")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub encrypted_data: Vec<u8>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: PalformDatabaseID<IDSubmission>,
    pub for_token: Option<PalformDatabaseID<IDFillAccessToken>>,
    pub form_id: PalformDatabaseID<IDForm>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::fill_access_token::Entity",
        from = "Column::ForToken",
        to = "super::fill_access_token::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    FillAccessToken,
    #[sea_orm(
        belongs_to = "super::form::Entity",
        from = "Column::FormId",
        to = "super::form::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Form,
    #[sea_orm(has_many = "super::webhook_job::Entity")]
    WebhookJob,
}

impl Related<super::fill_access_token::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FillAccessToken.def()
    }
}

impl Related<super::form::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Form.def()
    }
}

impl Related<super::webhook_job::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebhookJob.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
