//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use palform_tsid::{resources::{IDForm, IDWebhook}, tsid::PalformDatabaseID};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "webhook")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: PalformDatabaseID<IDWebhook>,
    pub form_id: PalformDatabaseID<IDForm>,
    pub endpoint: String,
    pub signing_secret: String,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::form::Entity",
        from = "Column::FormId",
        to = "super::form::Column::Id",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    Form,
    #[sea_orm(has_many = "super::webhook_job::Entity")]
    WebhookJob,
}

impl Related<super::form::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Form.def()
    }
}

impl Related<super::webhook_job::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebhookJob.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
