[package]
name = "palform-backend"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5", features = ["json", "uuid"] }
rocket_cors = "0.6"
sea-orm = { version = "1.0", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }
figment = { version = "0.10", features = ["env"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
openidconnect = { version = "3.5", features = [
    "reqwest",
    "rustls-tls",
    "accept-rfc3339-timestamps",
] }
thiserror = "2.0"
url = { version = "2", features = ["serde"] }
rocket_okapi = { version = "0.9", features = ["rapidoc"] }
schemars = { version = "0.8", features = ["url"] }
chrono = "0.4"
rand = "0.8"
log = "0.4"
base64 = "0.22"
sequoia-openpgp = { version = "2.0", default-features = false, features = [
    "crypto-rust",
    "allow-variable-time-crypto",
    "allow-experimental-crypto",
] }
lettre = { version = "0.11", default-features = false, features = [
    "builder",
    "smtp-transport",
    "tokio1-rustls-tls",
] }
reqwest = { version = "0.12", default-features = false, features = [
    "json",
    "http2",
    "rustls-tls",
] }
rust-s3 = { version = "0.35", default-features = false, features = [
    "tokio-rustls-tls",
] }
argon2 = "0.5.3"
validator = { version = "0.19", features = ["derive"] }
totp-rs = { version = "5.6" }
rust-i18n = { version = "3" }
accept-language = { version = "3" }
clap = { default-features = false, features = [
    "std",
    "help",
], version = "4.5.21" }
faster-hex = "0.10.0"
ring = "0.17"
webauthn-rs = { version = "0.5", features = [
    "danger-allow-state-serialisation",
] }

async-stripe = { version = "0.40", default-features = false, features = [
    "runtime-tokio-hyper-rustls",
] }
csv = { version = "1.3.1", optional = true }
bytes = { version = "1.8", optional = true }
nodit = { version = "0.9.2", optional = true }

keshvar = { version = "0.5.0", optional = true, features = ["emojis"] }

palform-migration = { path = "../migration" }
palform-entities = { path = "../entities" }
palform-client-common = { path = "../client-common", default-features = false, features = [
    "backend",
] }
palform-tsid = { path = "../tsid" }
palform-crypto = { path = "../crypto", default-features = false }

[features]
default = ["saas", "country-metadata"]
saas = [
    "async-stripe/billing",
    "async-stripe/checkout",
    "async-stripe/connect",
    "async-stripe/webhook-events",
    "dep:csv",
    "dep:bytes",
    "dep:nodit",
]
country-metadata = ["dep:keshvar"]
