[package]
name = "palform-tsid"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
prefixed-tsid = { version = "0.1.0", default-features = false }

[features]
default = ["sea-orm", "rocket", "serde", "schemars", "ts-rs"]
sea-orm = ["prefixed-tsid/sea-orm"]
rocket = ["prefixed-tsid/rocket"]
serde = ["prefixed-tsid/serde"]
schemars = ["prefixed-tsid/schemars"]
ts-rs = ["prefixed-tsid/ts-rs"]
