[package]
name = "palform-client-common"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0.201", features = ["derive"] }
serde_json = { version = "1.0.117" }
anyhow = "1.0.83"
csv = "1.3.0"
sequoia-openpgp = { version = "1.20.0", default-features = false, features = [
    "crypto-rust",
    "allow-variable-time-crypto",
    "allow-experimental-crypto",
] }
rand = { version = "0.8.5", default-features = false, features = ["getrandom"] }
thiserror = "1.0.57"
validator = "0.18.1"
geo = { version = "0.28.0", default-features = false }
chrono = { version = "0.4.38", features = ["serde"] }

serde-wasm-bindgen = { version = "0.6.5", optional = true }
wasm-bindgen = { version = "0.2.92", features = ["serde"], optional = true }
gloo-console = { version = "0.3.0", optional = true }
schemars = { version = "0.8.19", optional = true }
ts-rs = { version = "9.0.0", features = ["uuid-impl"], optional = true }
getrandom = { version = "0.2", features = ["js"], optional = true }
rocket = { version = "0.5.0", optional = true }
log = { version = "0.4.21", optional = true }
sea-orm = { version = "1.0", default-features = false, optional = true }

console_error_panic_hook = { version = "0.1", optional = true }

palform-tsid = { path = "../tsid", default-features = false }

[features]
default = ["frontend-js", "backend", "debug"]
frontend-js = [
    "dep:serde-wasm-bindgen",
    "dep:wasm-bindgen",
    "dep:gloo-console",
    "dep:ts-rs",
    "dep:getrandom",
    "palform-tsid/serde",
    "palform-tsid/ts-rs",
]
backend = [
    "dep:schemars",
    "dep:rocket",
    "dep:log",
    "dep:sea-orm",
    "palform-tsid/schemars",
    "palform-tsid/sea-orm",
    "palform-tsid/rocket",
    "palform-tsid/serde",
]
bench = ["backend"]
debug = ["dep:console_error_panic_hook"]
